### ISSUE TITLE
A very anti-privacy product

### ISSUE THREAD

**Issue by AlexanderMaxRanabel** [Inochi2D/facetrack-d#15]

**Comment by LunaTheFoxgirl** [comment]
I am not sure what you mean with this.
facetrack-d is used in privacy situations, eg. by allowing you to use virtual characters instead of your real self in video calls.

**Comment by AlexanderMaxRanabel** [comment]
This can be used by Goverments or basically organazition for face recognition purposes. My suggestion is to relicense this product ander AGPL 3.0

**Comment by LunaTheFoxgirl** [comment]
The AGPL does not prevent anything like that either. Not to mention, this does not do face recognition, only tracks facial landmarks, you can't get any recognition data out of it. Just blendshapes to apply to models.

**Comment by AlexanderMaxRanabel** [comment]
Glowie
